services:
  aidhs:
    image: meldproject/aidhs:latest
    platform: "linux/amd64"
    volumes:
      - volumes:/data
    environment: 
      - AIDHS_LICENSE=/run/secrets/aidhs_license.txt
    secrets:
      - aidhs_license.txt
    user: $DOCKER_USER
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: 0

secrets:
  aidhs_license.txt:
    file: ./aidhs_license.txt

